
version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/" 
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    versioning-strategy: "increase" 
    commit-message:
      prefix: "deps" 
    labels:
      - "dependencies" 
    groups:
      auto_update_minor_and_patch_dependencies:
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
  